apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sellers
  template:
    metadata:
      labels:
        app: sellers
    spec:
      containers:
        - image: kapatsyndianadockerid/sellerservic
          name: selers
          ports:
            - containerPort: 8089
              name: selers
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.1.2:5435/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"